version: 2
jobs:
  build:
    working_directory: /home/circleci/SummonerExpert
    docker:
      - image: circleci/ruby:2.3.4
    steps:
      - checkout

      - run:
          name: Setup Dependencies and Database
          command: |
            bundle install

      # Enables the remote environment necessary for deployment
      - setup_remote_docker

      - deploy:
          name: Deploy to Production
          command: |
            ./deploy.sh
