version: 2
jobs:
  build:
    working_directory: /home/circleci/SummonerExpert
    machine: true
    steps:
      # Enables the remote environment necessary for deployment
      - checkout

      - run:
          name: Build Test Image
          command: |
            rvm install 2.3.4
            rvm use 2.3.4 --default
            gem install bundler && bundle
            bundle exec rake secrets:decrypt
            export DEPLOY_TAG="${CIRCLE_BUILD_NUM}_${CIRCLE_SHA1:0:7}"
            docker build -f Dockerfile -t danreynolds/summonerexpert:$DEPLOY_TAG .
            docker-compose -f docker-compose.test.yml run app rspec

      - deploy:
          name: Deploy to Production
          command: ./deploy.sh
