version: 2
jobs:
  build:
    working_directory: /home/circleci/SummonerExpert
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      # Enables the remote environment necessary for deployment
      - setup_remote_docker

      - run:
          name: Setup Dependencies
          command: bundle exec rake secrets:decrypt

      - run:
          name: Run Tests
          command: docker-compose -f docker-compose.yml -f docker-compose.development.yml run app rspec

      - deploy:
          name: Deploy to Production
          command: ./deploy.sh
