version: 2
jobs:
  build:
    working_directory: /home/circleci/SummonerExpert
    docker:
      - image: circleci/ruby:2.3.4
        environment:
          RAILS_ENV: test
          RACK_ENV: test
    steps:
      - checkout
          name: Setup Dependencies
          command: |
            bundle install
      - run:
          name: Run Tests
          command: rspec

      - deploy:
          name: Deploy Check
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              exit 0
            fi

      # Enables the remote environment necessary for deployment
      - setup_remote_docker

      - deploy:
          name: Deploy to Production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./deploy.sh
            fi
