version: 2
jobs:
  build:
    working_directory: /home/circleci/SummonerExpert
    machine:
      image: circleci/classic:edge
    steps:
      # Enables the remote environment necessary for deployment
      - checkout

      - run:
          name: Install native libraries
          command: apt-get update -qq && apt-get install -y build-essential postgresql libpq-dev

      - run:
          name: Install dependencies
          command: gem install bundler && bundle

      - run:
          name: Load environment variables
          command: bundle exec rake secrets:decrypt

      - run:
          name: Run Tests
          command: docker-compose -f docker-compose.test.yml run app rspec

      - deploy:
          name: Deploy to production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./deploy.sh
            fi
