version: 2
jobs:
  build:
    working_directory: /home/circleci/SummonerExpert
    docker:
      - image: circleci/ruby:2.3
    steps:
      # Enables the remote environment necessary for deployment
      - setup_remote_docker
      - checkout

      - run:
          name: Build Test Image
          command: |
            bundle exec rake secrets:decrypt
            export DEPLOY_TAG="${CIRCLE_BUILD_NUM}_${CIRCLE_SHA1:0:7}"
            docker build -f Dockerfile -t danreynolds/summonerexpert:$DEPLOY_TAG .
            docker-compose -f docker-compose.test.yml run app rspec

      - deploy:
          name: Deploy to Production
          command: ./deploy.sh
