version: 2
jobs:
  build:
    working_directory: /home/circleci/SummonerExpert
    machine:
      image: circleci/classic:edge
    steps:
      # Enables the remote environment necessary for deployment
      - checkout

      - run:
          name: Install Dependencies
          command: gem install bundler && bundle

      - run:
          name: Decrypt environment variables
          command: bundle exec rake secrets:decrypt

      - run:
          name: Build Development Image
          command: |
            docker build -f Dockerfile .

      - run:
          name: Run Tests
          command: docker-compose -f docker-compose.test.yml run app rspec

      - deploy:
          name: Deploy to Production
          command: ./deploy.sh
