version: 2
jobs:
  build:
    working_directory: /home/circleci/SummonerExpert
    docker:
      - image: danreynolds/summonerexpert_circle:0.0.1
    steps:
      - checkout

      # Enables the remote environment necessary for using docker-compose
      - setup_remote_docker

      - run:
          name: Run Tests
          command: docker-compose -f docker-compose.yml -f docker-compose.test.yml run app rspec

      - deploy:
          name: Deploy Check
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              exit 0
            fi

      - deploy:
          name: Deploy to Production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./deploy.sh
            fi
