version: '3'
services:
  app:
    image: danreynolds/summonerexpert:$DEPLOY_TAG
    ports:
      - 3000
    volumes:
      - ./.env:/app/.env
      - ./scheduler.log:/app/scheduler.log
      - ./scheduler-error.log:/app/scheduler-error.log
      - logs:/app/log/
    env_file:
      - .env
  db:
    volumes:
      - pgdata:/var/lib/postgresql/data
  nginx:
    ports:
      - 80:80
      - 443:443
    networks:
      default:
    volumes:
      - logs:/etc/nginx/log/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - webroot:/usr/share/nginx/html
      - letsencrypt:/etc/nginx/letsencrypt
      - /etc/ssl/certs/dhparam.pem:/etc/nginx/letsencrypt/dhparam.pem
  letsencrypt:
    image: certbot/certbot:latest
    volumes:
      - webroot:/usr/share/nginx/html
      - letsencrypt:/etc/letsencrypt/live/api.summonerexpert.com
volumes:
  logs:
  pgdata:
  webroot:
  letsencrypt:
