version: '3'
services:
  redis:
    command: [redis-server, /usr/local/etc/redis/redis.conf, --requirepass, $REDIS_PASSWORD]
    image: "redis:latest"
    volumes:
      - redis:/var/lib/redis/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./dump.rdb:/usr/local/etc/redis/dump.rdb
  app:
    depends_on:
      - redis
    env_file:
      - .env
    expose:
      - 3000
  nginx:
    image: nginx
    depends_on:
      - app
volumes:
  redis:
