version: '3'
services:
  app:
    image: danreynolds/summonerexpert:$DEPLOY_TAG
    ports:
      - 3000
    volumes:
      - ./.env:/app/.env
      - ./scheduler.txt:/app/scheduler.txt
      - logs:/app/log/
    environment:
      - ENV_KEY=$ENV_KEY
      - DEPLOY_TAG=$DEPLOY_TAG
      - REDIS_PASSWORD=$REDIS_PASSWORD
    env_file:
      - .env
  nginx:
    ports:
      - 80
    networks:
      default:
      nginx_default:
        aliases:
          - SUMMONEREXPERT
    volumes:
      - redis:/data
      - logs:/etc/nginx/log/
      - ./nginx.upstream.conf:/etc/nginx/conf.d/default.conf
volumes:
  redis:
  logs:
networks:
  nginx_default:
    external: true
