version: '3'
services:
  app:
    image: danreynolds/summonerexpert:$DEPLOY_TAG
    ports:
      - 3000
    volumes:
      - ./.env:/app/.env
      - ./scheduler.log:/app/scheduler.log
      - ./scheduler-error.log:/app/scheduler-error.log
      - logs:/app/log/
    environment:
      - ENV_KEY=$ENV_KEY
      - DEPLOY_TAG=$DEPLOY_TAG
      - REDIS_PASSWORD=$REDIS_PASSWORD
    env_file:
      - .env
  nginx:
    ports:
      - 80:80
      - 443:443
    networks:
      default:
    volumes:
      - redis:/data
      - logs:/etc/nginx/log/
      - ./nginx.upstream.conf:/etc/nginx/conf.d/default.conf
volumes:
  redis:
  logs:
