version: '3'
services:
  app:
    image: danreynolds/summonerexpert:$DEPLOY_TAG
    ports:
      - 3000
    volumes:
      - ./.env:/app/.env
      - ./scheduler.log:/app/scheduler.log
      - ./scheduler-error.log:/app/scheduler-error.log
      - logs:/app/log/
    environment:
      - ENV_KEY=$ENV_KEY
      - DEPLOY_TAG=$DEPLOY_TAG
      - REDIS_PASSWORD=$REDIS_PASSWORD
    env_file:
      - .env
  nginx:
    ports:
      - 80:80
      - 443:443
    networks:
      default:
    volumes:
      - /etc/letsencrypt/live/api.summonerexpert.com/priv.pem:/etc/nginx/summonerexpert_privkey.pem
      - /etc/letsencrypt/live/api.summonerexpert.com/chain.pem:/etc/nginx/summonerexpert_chain.pem
      - /etc/letsencrypt/live/api.summonerexpert.com/fullchain.pem:/etc/nginx/summonerexpert_fullchain.pem
      - /etc/ssl/dhparam.pem:/etc/nginx/dhparam.pem
      - logs:/etc/nginx/log/
      - ./nginx.upstream.conf:/etc/nginx/conf.d/default.conf
volumes:
  logs:
