version: '3'
services:
  app:
    image: danreynolds/summonerexpert:$DEPLOY_TAG
    environment:
      - ENV_KEY=$ENV_KEY
      - DEPLOY_TAG=$DEPLOY_TAG
      - REDIS_PASSWORD=$REDIS_PASSWORD
    env_file:
      - .env
