version: '3'
services:
  app:
    image: danreynolds/summonerexpert:$DEPLOY_TAG
    environment:
      - ENV_KEY=$ENV_KEY
      - DEPLOY_TAG=$DEPLOY_TAG
      - REDIS_PASSWORD=$REDIS_PASSWORD
  nginx:
    ports:
      - 80
    networks:
      default:
      nginx_default:
        aliases:
          - SUMMONEREXPERT
    volumes:
      - logs:/etc/nginx/log/
      - ./nginx.upstream.conf:/etc/nginx/conf.d/default.conf
volumes:
  logs:
networks:
  nginx_default:
    external: true
