champions:
  title:
    - '{name} has the illustrious title of {title}.'
    - 'That champ and I go way back, if I had to call him anything it would be {name} {title}.'
    - '{name} has the title of {title}.'
  lore:
    - 'I will tell you about the history of {name}. Stop me if you have heard it: {lore}'
    - '{name} has such an interesting past. Here it is, stop me if you have heard it: {lore}'
  ability:
    - "{champion_name}'s {position} ability is called {ability_name}. {description}"
    - "Here is a description of {ability_name}, {champion_name}'s {position} ability: {description}"
  allytips:
    - "Here's something you should know about {name}: {tip}"
    - "Many times have I fought with {name} by my side. This is what I would take to heart: {tip}"
    - "I know {name} personally, you should know the following: {tip}"
  enemytips:
    - "I have seen {name} fall in battle before and this is what I would recommend: {tip}"
    - "While strong, {name} is not invincible. Remember the following: {tip}"
  ability_order:
    - 'The {metric} ability order for {name} {role} in {elo} is {ability_order}.'
    - 'As {name} {role}, the {metric} ability ordering is {ability_order} in {elo}.'
  role_performance_summary:
    - '{name} is doing {position_change} this patch in {role} and is ranked {position} out of {total_positions} with a {kda} KDA, {win_rate} win rate and a {ban_rate} ban rate in {elo} division.'
    - '{name} got {position_change} this patch and is ranked {position} out of {total_positions} in {role} with a {kda} KDA, {win_rate} win rate and a {ban_rate} ban rate in {elo} divison.'
  ranking:
    - 'The {list_position}{list_size}{champion_conjugation} with the {list_order} {position} in {role} from {elo} division {names_conjugation} {names}.'
  cooldown:
    - "The cooldown of {name}'s {ability_position} ability, {ability_name}, is {ability_cooldown} seconds at rank {rank}."
    - "{name}'s {ability_position} ability, {ability_name}, has a cooldown of {ability_cooldown} at rank {rank}."
  matchup:
    single_role:
      general:
        - '{name1} and {name2} have {champ1_result} and {champ2_result} {position} respectively playing {role1} in {elo} division.'
      winrate:
        - '{name1} and {name2} have a {champ1_result}% and {champ2_result}% {position} respectively playing {role1} in {elo} division.'
    duo_role:
      general:
        - '{name1} averages {champ1_result} {position} in {role1}, {match_result} than {name2} who averages {champ2_result} {position} when playing {role2} in {elo} division.'
      winrate:
        - '{name1} averages a {champ1_result}% {position} in {role1}, {match_result} than {name2} who averages a {champ2_result}% {position} when playing {role2} in {elo} division.'
    synergy:
      general:
        - '{name1} averages {champ1_result} {position} in {role1} when playing with {name2} {role2} in {elo}.'
      winrate:
        - '{name1} averages a {champ1_result}% {position} in {role1} when playing alongside {name2} {role2} in {elo}.'
  matchup_ranking:
    single_role:
      - 'The {list_position}{list_size}{champion_conjugation} with the {list_order} {position} against {name} {named_role} in {elo} division {names_conjugation} {ranked_names}.'
    duo_role:
      - 'The {list_position}{list_size}{champion_conjugation} with the {list_order} {position} when playing {unnamed_role} against {name} {named_role} in {elo} division {names_conjugation} {ranked_names}.'
    synergy:
      - 'The {list_position}{list_size}{champion_conjugation} with the {list_order} {position} when playing {unnamed_role} with {name} {named_role} in {elo} division {names_conjugation} {ranked_names}.'
  build:
    - 'The {metric} build for {name} {role} in {elo} division is {item_names}.'
  stats:
    - '{name} has {stat} {stat_name} at level {level}.'
items:
  build:
    - 'The items used to build {name} are {item_names}.'
  description:
    - "I have seen many champions use {name} on the field of battle. It costs {total_cost} gold and can be sold for {sell_cost}. Here is what it does:\n {description}"
