champions:
  title:
    - '{name} has the illustrious title of {title}.'
    - 'That champ and I go way back, if I had to call him anything it would be {name} {title}.'
    - '{name} has the title of {title}.'
  lore:
    - 'I will tell you about the history of {name}. Stop me if you have heard it: {lore}'
    - '{name} has such an interesting past. Here it is, stop me if you have heard it: {lore}'
  ability:
    - "{champion_name}'s {position} ability is called {ability_name}. {description}"
    - "Here is a description of {ability_name}, {champion_name}'s {position} ability: {description}"
  allytips:
    - "Here's something you should know about {name}: {tip}"
    - "Many times have I fought with {name} by my side. This is what I would take to heart: {tip}"
    - "I know {name} personally, you should know the following: {tip}"
  enemytips:
    - "I have seen {name} fall in battle before and this is what I would recommend: {tip}"
    - "While strong, {name} is not invincible. Remember the following: {tip}"
  ability_order:
    - 'The {metric} ability order for {name} {role} in {elo} is {ability_order}.'
    - 'As {name} {role}, the {metric} ability ordering is {ability_order} in {elo}.'
  role_performance_summary:
    - '{name} is doing {position_change} this patch in {role} and is ranked {position} out of {total_positions} with a {kda} KDA, {win_rate} win rate and a {ban_rate} ban rate in {elo} division.'
    - '{name} got {position_change} this patch and is ranked {position} out of {total_positions} in {role} with a {kda} KDA, {win_rate} win rate and a {ban_rate} ban rate in {elo} divison.'
  errors:
    does_not_play:
      - "There is no recommended way to play {name} {role} in {elo}."
      - "I have not seen {name} {role} enough in {elo} to give any useful feedback."
  followups:
