season: SEASON2017
summoner:
  ranked: https://na.api.pvp.net/api/lol/na/v2.5/league/by-summoner
  champions: https://na.api.pvp.net/api/lol/na/v1.3/stats/by-summoner
  id: https://na.api.pvp.net/api/lol/na/v1.4/summoner/by-name
  details: https://na.api.pvp.net/api/lol/na/v1.3/stats/by-summoner
champions: https://global.api.pvp.net/api/lol/static-data/na/v1.2/champion?champData=all
items: https://global.api.pvp.net/api/lol/static-data/na/v1.2/item?itemListData=stats
