season: SEASON2017
summoner:
  ranked: https://{region}.api.pvp.net/api/lol/{region}/v2.5/league/by-summoner/{id}
  champions: https://{region}.api.pvp.net/api/lol/{region}/v1.3/stats/by-summoner/{id}/ranked
  id: https://{region}.api.pvp.net/api/lol/{region}/v1.4/summoner/by-name
  details: https://{region}.api.pvp.net/api/lol/{region}/v1.3/stats/by-summoner
champions: https://global.api.pvp.net/api/lol/static-data/na/v1.2/champion?champData=all
items: https://global.api.pvp.net/api/lol/static-data/na/v1.2/item?itemListData=stats
