summoner:
  matches: https://{region}.api.riotgames.com/lol/match/v3/matchlists/by-account/{id}
  recent_matches: https://{region}.api.riotgames.com/lol/match/v3/matchlists/by-account/{id}/recent
  ranked: https://{region}.api.pvp.net/api/lol/{region}/v2.5/league/by-summoner/{id}
  champions: https://{region}.api.pvp.net/api/lol/{region}/v1.3/stats/by-summoner/{id}/ranked
  id: https://{region}.api.riotgames.com/lol/summoner/v3/summoners/by-name
  queues: https://{region}.api.riotgames.com/lol/league/v3/positions/by-summoner/{id}
champions: https://na1.api.riotgames.com/lol/static-data/v3/champions?locale=en_US&dataById=false{tags}
items: https://na1.api.riotgames.com/lol/static-data/v3/items?locale=en_US&tags=all
spells: https://na1.api.riotgames.com/lol/static-data/v3/summoner-spells?locale=en_US&dataById=true&tags=all
match: https://na1.api.riotgames.com/lol/match/v3/matches/{id}
